blacklist:
- Левиафан
- Йети
- Коровка из Коровёнки
- Житель Края
- Злой Тыков
bosses_cooldown:
    Королевский зомби: 20
    Холуй: 45
    Сточный слизень: 60
    Фенрир: 90
    Все Всадники апокалипсиса: 150
    Матка: 90
    Коровка из Коровёнки: 150
    Левиафан: 150
    Йети: 180
    Житель Края: 240
    Злой Тыков: 360
notification_duration: 3
