bosses_cooldown:
  Королевский зомби: 20
  Холуй: 45
  Сточный слизень: 60
  Фенрир: 90
  Всадники апокалипсиса: 90
  Матка: 105
  Коровка из Коровёнки: 150
  Левиафан: 150
  Йети: 180
  Житель края: 240
  Небесный владыка: 360
  Хранитель подводного мира: 240
notification_duration: 3
mines_cooldown:
  Шерстяная шахта: 240
  Земляная шахта (1): 195
  Земляная шахта (5): 240
  Земляная шахта (6): 900
  Каменная шахта: 720
  Карьер: 600
  Адская шахта: 480
  Сумеречный лес: 1380
  Бездна: 1500
  Паучье логово: 1200
  Грибоедово ущелье: 900
  Логово Йети: 600
colored: true
